# Generated by Django 3.0.6 on 2020-05-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200516_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='taskdata',
        ),
        migrations.AddField(
            model_name='userdata',
            name='taskdata',
            field=models.ManyToManyField(to='todolist.TaskNstatus'),
        ),
    ]
