# Generated by Django 3.0.6 on 2020-05-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200516_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='taskdata',
        ),
        migrations.AddField(
            model_name='userdata',
            name='taskdata',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='TaskNstatus',
        ),
    ]
